const VERSION='V.1.1.0';
const SOCIAL={roblox:'https://www.roblox.com/users/4818300014/profile',instagram:'https://www.instagram.com/manvith_1005?igsh=bWppbzBxZWc9emhv',discord:'https://discord.gg/nGqKXKNKsW'};
const FEEDBACK_ENDPOINT='https://orange-waterfall-e488.linganagoudapatilpatil.workers.dev';
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const sortNum=(a,b)=>(a.number||0)-(b.number||0);
const gameSlides={};
function icon(type){if(type==='roblox')return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5.2 2.8 21.2 7l-4.2 16-16-4.2 4.2-16Zm3.1 5.1-1.6 6.1 6.1 1.6 1.6-6.1 6.1 1.6Z"/></svg>';if(type==='instagram')return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5Zm0 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3H7Zm5 3.5A4.5 4.5 0 1 1 7.5 12 4.5 4.5 0 0 1 12 7.5Zm0 2A2.5 2.5 0 1 0 14.5 12 2.5 2.5 0 0 0 12 9.5ZM17.3 6.2a1.1 1.1 0 1 1-1.1 1.1 1.1 0 0 1-1.1-1.1Z"/></svg>';return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M19.5 5.2A16.5 16.5 0 0 0 15.4 4l-.5 1a15.1 15.1 0 0 0-5.8 0l-.5-1a16.5 16.5 0 0 0-4.1 1.2C1.9 8.2 1.2 11 1.4 13.8A16.7 16.7 0 0 0 6.5 16l1.2-1.5c-.7-.2-1.3-.6-1.9-1 2.4 1.1 5.2 1.6 8.1 1.6s5.7-.5 8.1-1.6c-.6.4-1.2.8-1.9 1l1.2 1.5a16.7 16.7 0 0 0 5.1-2.2c.3-3.3-.6-6.1-4.9-8.6ZM8.2 12.3c-.8 0-1.5-.7-1.5-1.6s.7-1.6 1.5-1.6 1.5.7 1.5 1.6-.7 1.6-1.5 1.6Zm7.6 0c-.8 0-1.5-.7-1.5-1.6s.7-1.6 1.5-1.6 1.5.7 1.5 1.6-.7 1.6-1.5 1.6Z"/></svg>'}
function feedbackIcon(){return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H9l-5 4v-4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Zm3 5h10V7H7v2Zm0 4h7v-2H7v2Z"/></svg>'}
function socialNav(){return `<div class="socials"><a class="social-btn" href="${SOCIAL.roblox}" target="_blank" rel="noopener">${icon('roblox')}<span>Roblox</span></a><a class="social-btn" href="${SOCIAL.instagram}" target="_blank" rel="noopener">${icon('instagram')}<span>Instagram</span></a><a class="social-btn" href="${SOCIAL.discord}" target="_blank" rel="noopener">${icon('discord')}<span>Discord</span></a><button class="social-btn feedback-btn" type="button" onclick="openFeedback()">${feedbackIcon()}<span>Feedback</span></button></div>`}
function nav(active=''){return `<header class="nav"><a class="brand" href="index.html">ZYREXCORE</a><div class="nav-right"><nav class="nav-links"><a href="games.html" class="${active==='games'?'active':''}">Games</a><a href="gfx.html" class="${active==='gfx'?'active':''}">GFX</a><a href="models.html" class="${active==='models'?'active':''}">3D Models</a></nav>${socialNav()}</div></header>`}
function feedbackModal(){return `<div class="feedback-overlay" id="feedbackOverlay" aria-hidden="true"><div class="feedback-modal" role="dialog" aria-modal="true" aria-labelledby="feedbackTitle"><button class="feedback-close" type="button" onclick="closeFeedback()" aria-label="Close">×</button><div class="eyebrow">ZYREXCORE // FEEDBACK</div><h2 id="feedbackTitle">Tell me what you think.</h2><p class="feedback-subtitle">Your feedback helps improve the portfolio.</p><form id="feedbackForm" onsubmit="submitFeedback(event)"><label>Discord Username<input id="feedbackDiscord" maxlength="100" autocomplete="off" placeholder="your_discord_username" required></label><label>Roblox Username <span>(not Display Name)</span><input id="feedbackRoblox" maxlength="100" autocomplete="off" placeholder="your_roblox_username" required></label><label>Your Opinion<textarea id="feedbackMessage" maxlength="2000" rows="7" placeholder="Write your feedback, opinion or suggestions..." required></textarea></label><input id="feedbackTrap" class="feedback-trap" tabindex="-1" autocomplete="off"><div class="feedback-status" id="feedbackStatus" aria-live="polite"></div><div class="feedback-actions"><button class="btn" type="button" onclick="closeFeedback()">Cancel</button><button class="btn primary" id="feedbackSubmit" type="submit">Send Feedback →</button></div></form></div></div>`}
function initKineticHero(){const wrap=document.querySelector('.hero-brand-wrap');const brand=document.querySelector('.hero-brand');if(!wrap||!brand||wrap.dataset.kinetic==='1')return;wrap.dataset.kinetic='1';const text=brand.textContent.trim();brand.setAttribute('data-text',text);brand.innerHTML=[...text].map((ch,i)=>`<span class="hero-letter" style="--i:${i}">${ch===' '?'&nbsp;':ch}</span>`).join('');const top=document.createElement('div');top.className='hero-marquee hero-marquee-top';top.setAttribute('aria-hidden','true');top.innerHTML=`<span>${text} · CREATE · BUILD · ${text} · CREATE · BUILD ·</span><span>${text} · CREATE · BUILD · ${text} · CREATE · BUILD ·</span>`;const bottom=document.createElement('div');bottom.className='hero-marquee hero-marquee-bottom';bottom.setAttribute('aria-hidden','true');bottom.innerHTML=`<span>MANVITH PATIL · DEVELOPER · CREATOR · ${text} · DEVELOPER · CREATOR ·</span><span>MANVITH PATIL · DEVELOPER · CREATOR · ${text} · DEVELOPER · CREATOR ·</span>`;wrap.prepend(top);wrap.append(bottom);const beam=document.createElement('div');beam.className='hero-scan';beam.setAttribute('aria-hidden','true');wrap.append(beam)}
function initPreviewScroll(){document.querySelectorAll('.grid').forEach(grid=>{if(grid.dataset.previewScroll==='1')return;grid.dataset.previewScroll='1';const wrap=document.createElement('div');wrap.className='preview-scroll-wrap';grid.parentNode.insertBefore(wrap,grid);wrap.appendChild(grid);const prev=document.createElement('button');prev.className='preview-scroll-btn preview-scroll-prev';prev.type='button';prev.setAttribute('aria-label','Previous preview');prev.innerHTML='‹';const next=document.createElement('button');next.className='preview-scroll-btn preview-scroll-next';next.type='button';next.setAttribute('aria-label','Next preview');next.innerHTML='›';wrap.append(prev,next);const cards=[...grid.children].filter(el=>el.classList.contains('card'));let index=0;const update=()=>{if(window.innerWidth>600){cards.forEach(c=>c.hidden=false);prev.hidden=true;next.hidden=true;return}cards.forEach((c,i)=>{c.hidden=i!==index});prev.hidden=cards.length<2;next.hidden=cards.length<2;prev.disabled=index<=0;next.disabled=index>=cards.length-1};prev.addEventListener('click',()=>{if(index>0){index--;update()}});next.addEventListener('click',()=>{if(index<cards.length-1){index++;update()}});window.addEventListener('resize',update);update()})}
function bootChrome(active){document.body.insertAdjacentHTML('afterbegin',`<div class="version-badge" aria-label="Portfolio version">${VERSION}</div><div class="cursor-light" id="cursorLight"></div>`+nav(active));document.body.insertAdjacentHTML('beforeend','<div class="lightbox" id="lightbox"><button class="close" onclick="closeLightbox()">Close ✕</button><img id="lightboxImg" alt="Preview"></div>'+feedbackModal()+'<div class="feedback-toast" id="feedbackToast" role="status" aria-live="polite"></div>');initKineticHero();initPreviewScroll();const c=document.getElementById('cursorLight');window.addEventListener('pointermove',e=>{c.style.left=e.clientX+'px';c.style.top=e.clientY+'px'})}
function showFeedbackToast(message,type='info'){const t=document.getElementById('feedbackToast');if(!t)return;t.textContent=message;t.className=`feedback-toast show ${type}`;clearTimeout(window.feedbackToastTimer);window.feedbackToastTimer=setTimeout(()=>{t.classList.remove('show')},3500)}
function openFeedback(){const o=document.getElementById('feedbackOverlay');if(!o)return;o.classList.add('open');o.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');setTimeout(()=>document.getElementById('feedbackDiscord')?.focus(),50)}
function closeFeedback(){const o=document.getElementById('feedbackOverlay');if(!o)return;o.classList.remove('open');o.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
async function submitFeedback(e){e.preventDefault();const form=e.currentTarget;const status=document.getElementById('feedbackStatus');const submit=document.getElementById('feedbackSubmit');if(document.getElementById('feedbackTrap').value)return;const discord=document.getElementById('feedbackDiscord').value.trim();const roblox=document.getElementById('feedbackRoblox').value.trim();const message=document.getElementById('feedbackMessage').value.trim();status.textContent='';if(!discord||!roblox||!message){showFeedbackToast('Please fill in all fields.','error');return}const last=Number(localStorage.getItem('zyrex_feedback_last')||0);if(Date.now()-last<30000){showFeedbackToast('Please wait 30 seconds before sending another feedback.','error');return}submit.disabled=true;showFeedbackToast('Sending feedback...','info');try{const r=await fetch(FEEDBACK_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({discordUsername:discord,robloxUsername:roblox,message})});if(!r.ok)throw Error('Request failed');localStorage.setItem('zyrex_feedback_last',String(Date.now()));form.reset();showFeedbackToast('Feedback sent successfully. Thank you!','success');setTimeout(closeFeedback,1200)}catch(err){showFeedbackToast('Could not send feedback. Please try again later.','error')}finally{submit.disabled=false}}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeFeedback()});
async function manifest(){const r=await fetch(`portfolio-manifest.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('Portfolio manifest could not be loaded.');return r.json()}
function imgPath(file){return 'assets/'+String(file).split('/').map(encodeURIComponent).join('/')}
function card(item,label,click=false){return `<article class="card reveal" ${click?`onclick="openLightbox('${esc(imgPath(item.file))}')" style="cursor:zoom-in"`:''}><div class="media"><img src="${esc(imgPath(item.file))}" alt="${esc(item.title)}" loading="lazy" decoding="async"></div><div class="card-body"><div class="kicker">${esc(label)}</div><h3>${esc(item.title)}</h3></div></article>`}
function empty(text){return `<div class="empty">${esc(text)}</div>`}
async function renderAssets(type,containerId,label){const box=document.getElementById(containerId);try{const all=await manifest();const items=all.filter(x=>x.type===type).sort(sortNum);box.innerHTML=items.length?items.map(x=>card(x,label,type!=='game')).join(''):empty('ADDING WHEN I\'M FEELING LIKE IT')}catch(e){box.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function gameCard(g){const imgs=Array.isArray(g.thumbnails)?g.thumbnails.filter(Boolean).slice(0,10):[];const id=`game-${g.number}`;gameSlides[g.number]={imgs,index:0};const hasLink=g.url&&g.url!=='#';const media=imgs.length?`<div class="game-carousel" id="${id}"><img class="game-slide" id="${id}-img" src="${esc(imgs[0])}" alt="${esc(g.title)}" loading="lazy" decoding="async">${imgs.length>1?`<div class="slide-count" id="${id}-count">1 / ${imgs.length}</div>`:''}</div>`:`<div class="game-placeholder"><span>ROBLOX</span><small>${g.url==='#'?'LINK PENDING':'THUMBNAILS UNAVAILABLE'}</small></div>`;return `<article class="card reveal"><div class="media game-media">${media}</div><div class="card-body"><div class="kicker">ROBLOX GAME ${String(g.number).padStart(2,'0')}</div><h3 class="game-name">${esc(g.title)}</h3><p class="game-description">${esc(g.description||'No description available from Roblox.')}</p><div class="card-actions">${hasLink?`<a class="btn primary" href="${esc(g.url)}" target="_blank" rel="noopener">▶ Play on Roblox</a>`:`<span class="btn" style="opacity:.5;cursor:not-allowed">Link Pending</span>`}</div></div></article>`}
function changeGameSlide(number,dir){const s=gameSlides[number];if(!s||s.imgs.length<2)return;s.index=(s.index+dir+s.imgs.length)%s.imgs.length;const img=document.getElementById(`game-${number}-img`);const count=document.getElementById(`game-${number}-count`);if(img)img.src=s.imgs[s.index];if(count)count.textContent=`${s.index+1} / ${s.imgs.length}`}
function startGameCarousel(number){const s=gameSlides[number];if(!s||s.imgs.length<2)return;setInterval(()=>changeGameSlide(number,1),5000)}
async function renderGames(containerId,limit=Infinity){const box=document.getElementById(containerId);try{const all=await manifest();const games=all.filter(x=>x.type==='game').sort(sortNum).slice(0,limit);box.innerHTML=games.length?games.map(gameCard).join(''):empty('ADDING WHEN I\'M FEELING LIKE IT');games.forEach(g=>startGameCarousel(g.number))}catch(e){box.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function openLightbox(src){const l=document.getElementById('lightbox');document.getElementById('lightboxImg').src=src;l.classList.add('open')}function closeLightbox(){document.getElementById('lightbox').classList.remove('open')}
